// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.Context;

namespace Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210714114433_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Entities.STI", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Birim")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("EvrakNo")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("EvrakNo");

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("decimal(25,6)")
                        .HasColumnName("Fiyat");

                    b.Property<short>("IslemTur")
                        .HasColumnType("smallint");

                    b.Property<int>("MalID")
                        .HasMaxLength(30)
                        .HasColumnType("int");

                    b.Property<decimal>("Miktar")
                        .HasColumnType("decimal(25,6)")
                        .HasColumnName("Miktar");

                    b.Property<int>("Tarih")
                        .HasColumnType("int");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("decimal(25,6)")
                        .HasColumnName("Tutar");

                    b.HasKey("ID");

                    b.HasIndex("MalID");

                    b.ToTable("STI");
                });

            modelBuilder.Entity("Domain.Entities.STK", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MalAdi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MalKodu")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("ID");

                    b.HasIndex("MalKodu")
                        .IsUnique();

                    b.ToTable("STk");
                });

            modelBuilder.Entity("Domain.Entities.STI", b =>
                {
                    b.HasOne("Domain.Entities.STK", "Mal")
                        .WithMany("Islemller")
                        .HasForeignKey("MalID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mal");
                });

            modelBuilder.Entity("Domain.Entities.STK", b =>
                {
                    b.Navigation("Islemller");
                });
#pragma warning restore 612, 618
        }
    }
}
